[package]
name = "external"
version = "0.1.0"

[dependencies]
winapi = { version = "0.3", features = [
	"winuser", "processthreadsapi", "handleapi", "synchapi", "winbase", "tlhelp32",
	"consoleapi", "errhandlingapi", "wingdi", "memoryapi", "winerror"
] }
